apiVersion: apps/v1
kind: Deployment
metadata:
  name: nessie
  namespace: lakehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nessie
  template:
    metadata:
      labels:
        app: nessie
    spec:
      containers:
        - name: nessie
          image: ghcr.io/projectnessie/nessie:0.85.1
          ports:
            - containerPort: 19120
          env:
            - name: NESSIE_VERSION_STORE_TYPE
              value: IN_MEMORY
---
apiVersion: v1
kind: Service
metadata:
  name: nessie
  namespace: lakehouse
spec:
  selector:
    app: nessie
  ports:
    - port: 19120
      targetPort: 19120