apiVersion: apps/v1
kind: Deployment
metadata:
  name: nessie
  namespace: lakehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nessie
  template:
    metadata:
      labels:
        app: nessie
    spec:
      containers:
        - name: nessie
          image: ghcr.io/projectnessie/nessie:0.85.1
          ports:
            - containerPort: 19120
              name: api
          env:
            - name: NESSIE_VERSION_STORE_TYPE
              value: IN_MEMORY
            # Adicionar outras variáveis de ambiente conforme necessário
            - name: QUARKUS_LOG_LEVEL
              value: INFO
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: api
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: api
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: nessie
  namespace: lakehouse
spec:
  selector:
    app: nessie
  ports:
    - name: api
      port: 19120
      targetPort: 19120