apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-lakehouse
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/lakehouse
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-lakehouse
  namespace: lakehouse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi